# Site settings
title: Mirna Majstorović - UX Designer and Web Developer
email: mirna.majstorovic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am prototyping web applications and designing and coding user interfaces in HTML, CSS and JavaScript.
  I like to make complex workflows simple, seamless, and pleasant and strive to deliver well thought-out designs, accompanied by clean, valid, reusable code.
baseurl: "" 
url: "http://ejla.github.io" # the base hostname & protocol for your site
twitter_username: mirna_m
github_username:  Ejla

# Build settings
markdown: kramdown
